name = "odd-base-e5e3"
main = "license_worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LICENSE_KV"
id      = "42f09113c9a64457b4422a3c489e2225"
# deployed 2026-06-06T06:29:49Z
